# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2022. Licensed under the AGPL and commercial licences.

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import obp_python
from obp_python.rest import ApiException
from obp_python.apis.documentation_api import DocumentationApi


class TestDocumentationApi(unittest.TestCase):
    """ DocumentationApi unit test stubs """

    def setUp(self):
        self.api = obp_python.apis.documentation_api.DocumentationApi()

    def tearDown(self):
        pass

    def test_o_b_pv1_4_0_get_bank_level_dynamic_resource_docs_obp(self):
        """
        Test case for o_b_pv1_4_0_get_bank_level_dynamic_resource_docs_obp

        Get Bank Level Dynamic Resource Docs.
        """
        pass

    def test_o_b_pv1_4_0_get_resource_docs_obp(self):
        """
        Test case for o_b_pv1_4_0_get_resource_docs_obp

        Get Resource Docs.
        """
        pass

    def test_o_b_pv1_4_0_get_resource_docs_swagger(self):
        """
        Test case for o_b_pv1_4_0_get_resource_docs_swagger

        Get Swagger documentation
        """
        pass

    def test_o_b_pv2_2_0_get_message_docs(self):
        """
        Test case for o_b_pv2_2_0_get_message_docs

        Get Message Docs
        """
        pass

    def test_o_b_pv3_0_0_get_api_glossary(self):
        """
        Test case for o_b_pv3_0_0_get_api_glossary

        Get Glossary of the API
        """
        pass

    def test_o_b_pv3_1_0_get_message_docs_swagger(self):
        """
        Test case for o_b_pv3_1_0_get_message_docs_swagger

        Get Message Docs Swagger
        """
        pass

    def test_o_b_pv4_0_0_get_scanned_api_versions(self):
        """
        Test case for o_b_pv4_0_0_get_scanned_api_versions

        Get scanned API Versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
