# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2022. Licensed under the AGPL and commercial licences.

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import obp_python
from obp_python.rest import ApiException
from obp_python.apis.consumer_api import ConsumerApi


class TestConsumerApi(unittest.TestCase):
    """ ConsumerApi unit test stubs """

    def setUp(self):
        self.api = obp_python.apis.consumer_api.ConsumerApi()

    def tearDown(self):
        pass

    def test_o_b_pv2_1_0_update_consumer_redirect_url(self):
        """
        Test case for o_b_pv2_1_0_update_consumer_redirect_url

        Update Consumer RedirectUrl
        """
        pass

    def test_o_b_pv3_0_0_delete_scope(self):
        """
        Test case for o_b_pv3_0_0_delete_scope

        Delete Consumer Scope
        """
        pass

    def test_o_b_pv3_1_0_enable_disable_consumers(self):
        """
        Test case for o_b_pv3_1_0_enable_disable_consumers

        Enable or Disable Consumers
        """
        pass

    def test_o_b_pv3_1_0_get_calls_limit(self):
        """
        Test case for o_b_pv3_1_0_get_calls_limit

        Get Call Limits for a Consumer
        """
        pass

    def test_o_b_pv3_1_0_get_consumer(self):
        """
        Test case for o_b_pv3_1_0_get_consumer

        Get Consumer
        """
        pass

    def test_o_b_pv3_1_0_get_consumers(self):
        """
        Test case for o_b_pv3_1_0_get_consumers

        Get Consumers
        """
        pass

    def test_o_b_pv3_1_0_get_consumers_for_current_user(self):
        """
        Test case for o_b_pv3_1_0_get_consumers_for_current_user

        Get Consumers (logged in User)
        """
        pass

    def test_o_b_pv4_0_0_add_scope(self):
        """
        Test case for o_b_pv4_0_0_add_scope

        Create Scope for a Consumer
        """
        pass

    def test_o_b_pv4_0_0_calls_limit(self):
        """
        Test case for o_b_pv4_0_0_calls_limit

        Set Calls Limit for a Consumer
        """
        pass

    def test_o_b_pv4_0_0_create_consumer(self):
        """
        Test case for o_b_pv4_0_0_create_consumer

        Post a Consumer
        """
        pass

    def test_o_b_pv4_0_0_get_scopes(self):
        """
        Test case for o_b_pv4_0_0_get_scopes

        Get Scopes for Consumer
        """
        pass


if __name__ == '__main__':
    unittest.main()
