# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.api.confirmation_of_funds_service__piis_api import ConfirmationOfFundsServicePIISApi  # noqa: E501
from obp_python.rest import ApiException


class TestConfirmationOfFundsServicePIISApi(unittest.TestCase):
    """ConfirmationOfFundsServicePIISApi unit test stubs"""

    def setUp(self):
        self.api = obp_python.api.confirmation_of_funds_service__piis_api.ConfirmationOfFundsServicePIISApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_o_bpv3_1_0_check_funds_available(self):
        """Test case for o_bpv3_1_0_check_funds_available

        Check Available Funds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
