# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.models.inline_response2003_swagger_string import InlineResponse2003SwaggerString  # noqa: E501
from obp_python.rest import ApiException


class TestInlineResponse2003SwaggerString(unittest.TestCase):
    """InlineResponse2003SwaggerString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003SwaggerString(self):
        """Test InlineResponse2003SwaggerString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = obp_python.models.inline_response2003_swagger_string.InlineResponse2003SwaggerString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
