# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2022. Licensed under the AGPL and commercial licences.

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import obp_python
from obp_python.rest import ApiException
from obp_python.apis.customer_api import CustomerApi


class TestCustomerApi(unittest.TestCase):
    """ CustomerApi unit test stubs """

    def setUp(self):
        self.api = obp_python.apis.customer_api.CustomerApi()

    def tearDown(self):
        pass

    def test_o_b_pv1_4_0_create_customer_message(self):
        """
        Test case for o_b_pv1_4_0_create_customer_message

        Create Customer Message
        """
        pass

    def test_o_b_pv1_4_0_get_crm_events(self):
        """
        Test case for o_b_pv1_4_0_get_crm_events

        Get CRM Events
        """
        pass

    def test_o_b_pv1_4_0_get_customer_messages(self):
        """
        Test case for o_b_pv1_4_0_get_customer_messages

        Get Customer Messages for a Customer
        """
        pass

    def test_o_b_pv2_0_0_add_kyc_check(self):
        """
        Test case for o_b_pv2_0_0_add_kyc_check

        Add KYC Check
        """
        pass

    def test_o_b_pv2_0_0_add_kyc_document(self):
        """
        Test case for o_b_pv2_0_0_add_kyc_document

        Add KYC Document
        """
        pass

    def test_o_b_pv2_0_0_add_kyc_media(self):
        """
        Test case for o_b_pv2_0_0_add_kyc_media

        Add KYC Media
        """
        pass

    def test_o_b_pv2_0_0_add_kyc_status(self):
        """
        Test case for o_b_pv2_0_0_add_kyc_status

        Add KYC Status
        """
        pass

    def test_o_b_pv2_0_0_add_social_media_handle(self):
        """
        Test case for o_b_pv2_0_0_add_social_media_handle

        Add Social Media Handle
        """
        pass

    def test_o_b_pv2_0_0_get_kyc_checks(self):
        """
        Test case for o_b_pv2_0_0_get_kyc_checks

        Get Customer KYC Checks
        """
        pass

    def test_o_b_pv2_0_0_get_kyc_documents(self):
        """
        Test case for o_b_pv2_0_0_get_kyc_documents

        Get Customer KYC Documents
        """
        pass

    def test_o_b_pv2_0_0_get_kyc_media(self):
        """
        Test case for o_b_pv2_0_0_get_kyc_media

        Get KYC Media for a customer
        """
        pass

    def test_o_b_pv2_0_0_get_kyc_statuses(self):
        """
        Test case for o_b_pv2_0_0_get_kyc_statuses

        Get Customer KYC statuses
        """
        pass

    def test_o_b_pv2_0_0_get_social_media_handles(self):
        """
        Test case for o_b_pv2_0_0_get_social_media_handles

        Get Customer Social Media Handles
        """
        pass

    def test_o_b_pv3_0_0_get_customers_for_user(self):
        """
        Test case for o_b_pv3_0_0_get_customers_for_user

        Get Customers for Current User
        """
        pass

    def test_o_b_pv3_1_0_create_credit_limit_request(self):
        """
        Test case for o_b_pv3_1_0_create_credit_limit_request

        Create Credit Limit Order Request
        """
        pass

    def test_o_b_pv3_1_0_create_customer_address(self):
        """
        Test case for o_b_pv3_1_0_create_customer_address

        Create Address
        """
        pass

    def test_o_b_pv3_1_0_create_meeting(self):
        """
        Test case for o_b_pv3_1_0_create_meeting

        Create Meeting (video conference/call)
        """
        pass

    def test_o_b_pv3_1_0_create_tax_residence(self):
        """
        Test case for o_b_pv3_1_0_create_tax_residence

        Create Tax Residence
        """
        pass

    def test_o_b_pv3_1_0_delete_customer_address(self):
        """
        Test case for o_b_pv3_1_0_delete_customer_address

        Delete Customer Address
        """
        pass

    def test_o_b_pv3_1_0_delete_tax_residence(self):
        """
        Test case for o_b_pv3_1_0_delete_tax_residence

        Delete Tax Residence
        """
        pass

    def test_o_b_pv3_1_0_get_credit_limit_request_by_request_id(self):
        """
        Test case for o_b_pv3_1_0_get_credit_limit_request_by_request_id

        Get Credit Limit Order Request By Request Id
        """
        pass

    def test_o_b_pv3_1_0_get_credit_limit_requests(self):
        """
        Test case for o_b_pv3_1_0_get_credit_limit_requests

        Get Credit Limit Order Requests 
        """
        pass

    def test_o_b_pv3_1_0_get_customer_addresses(self):
        """
        Test case for o_b_pv3_1_0_get_customer_addresses

        Get Customer Addresses
        """
        pass

    def test_o_b_pv3_1_0_get_customer_by_customer_id(self):
        """
        Test case for o_b_pv3_1_0_get_customer_by_customer_id

        Get Customer by CUSTOMER_ID
        """
        pass

    def test_o_b_pv3_1_0_get_customer_by_customer_number(self):
        """
        Test case for o_b_pv3_1_0_get_customer_by_customer_number

        Get Customer by CUSTOMER_NUMBER
        """
        pass

    def test_o_b_pv3_1_0_get_firehose_customers(self):
        """
        Test case for o_b_pv3_1_0_get_firehose_customers

        Get Firehose Customers
        """
        pass

    def test_o_b_pv3_1_0_get_meeting(self):
        """
        Test case for o_b_pv3_1_0_get_meeting

        Get Meeting
        """
        pass

    def test_o_b_pv3_1_0_get_meetings(self):
        """
        Test case for o_b_pv3_1_0_get_meetings

        Get Meetings
        """
        pass

    def test_o_b_pv3_1_0_get_tax_residence(self):
        """
        Test case for o_b_pv3_1_0_get_tax_residence

        Get Tax Residences of Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_address(self):
        """
        Test case for o_b_pv3_1_0_update_customer_address

        Update the Address of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_branch(self):
        """
        Test case for o_b_pv3_1_0_update_customer_branch

        Update the Branch of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_credit_limit(self):
        """
        Test case for o_b_pv3_1_0_update_customer_credit_limit

        Update the credit limit of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_credit_rating_and_source(self):
        """
        Test case for o_b_pv3_1_0_update_customer_credit_rating_and_source

        Update the credit rating and source of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_data(self):
        """
        Test case for o_b_pv3_1_0_update_customer_data

        Update the other data of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_email(self):
        """
        Test case for o_b_pv3_1_0_update_customer_email

        Update the email of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_identity(self):
        """
        Test case for o_b_pv3_1_0_update_customer_identity

        Update the identity data of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_mobile_number(self):
        """
        Test case for o_b_pv3_1_0_update_customer_mobile_number

        Update the mobile number of a Customer
        """
        pass

    def test_o_b_pv3_1_0_update_customer_number(self):
        """
        Test case for o_b_pv3_1_0_update_customer_number

        Update the number of a Customer
        """
        pass

    def test_o_b_pv4_0_0_create_customer_attribute(self):
        """
        Test case for o_b_pv4_0_0_create_customer_attribute

        Create Customer Attribute
        """
        pass

    def test_o_b_pv4_0_0_create_customer_message(self):
        """
        Test case for o_b_pv4_0_0_create_customer_message

        Create Customer Message
        """
        pass

    def test_o_b_pv4_0_0_create_or_update_customer_attribute_attribute_definition(self):
        """
        Test case for o_b_pv4_0_0_create_or_update_customer_attribute_attribute_definition

        Create or Update Customer Attribute Definition
        """
        pass

    def test_o_b_pv4_0_0_create_user_customer_links(self):
        """
        Test case for o_b_pv4_0_0_create_user_customer_links

        Create User Customer Link
        """
        pass

    def test_o_b_pv4_0_0_delete_customer_attribute(self):
        """
        Test case for o_b_pv4_0_0_delete_customer_attribute

        Delete Customer Attribute
        """
        pass

    def test_o_b_pv4_0_0_delete_customer_attribute_definition(self):
        """
        Test case for o_b_pv4_0_0_delete_customer_attribute_definition

        Delete Customer Attribute Definition
        """
        pass

    def test_o_b_pv4_0_0_delete_customer_cascade(self):
        """
        Test case for o_b_pv4_0_0_delete_customer_cascade

        Delete Customer Cascade
        """
        pass

    def test_o_b_pv4_0_0_delete_user_customer_link(self):
        """
        Test case for o_b_pv4_0_0_delete_user_customer_link

        Delete User Customer Link
        """
        pass

    def test_o_b_pv4_0_0_get_correlated_users_info_by_customer_id(self):
        """
        Test case for o_b_pv4_0_0_get_correlated_users_info_by_customer_id

        Get Correlated User Info by Customer
        """
        pass

    def test_o_b_pv4_0_0_get_customer_attribute_by_id(self):
        """
        Test case for o_b_pv4_0_0_get_customer_attribute_by_id

        Get Customer Attribute By Id
        """
        pass

    def test_o_b_pv4_0_0_get_customer_attribute_definition(self):
        """
        Test case for o_b_pv4_0_0_get_customer_attribute_definition

        Get Customer Attribute Definition
        """
        pass

    def test_o_b_pv4_0_0_get_customer_attributes(self):
        """
        Test case for o_b_pv4_0_0_get_customer_attributes

        Get Customer Attributes
        """
        pass

    def test_o_b_pv4_0_0_get_customer_messages(self):
        """
        Test case for o_b_pv4_0_0_get_customer_messages

        Get Customer Messages for a Customer
        """
        pass

    def test_o_b_pv4_0_0_get_customers_at_any_bank(self):
        """
        Test case for o_b_pv4_0_0_get_customers_at_any_bank

        Get Customers at Any Bank
        """
        pass

    def test_o_b_pv4_0_0_get_customers_by_customer_phone_number(self):
        """
        Test case for o_b_pv4_0_0_get_customers_by_customer_phone_number

        Get Customers by MOBILE_PHONE_NUMBER
        """
        pass

    def test_o_b_pv4_0_0_get_customers_minimal_at_any_bank(self):
        """
        Test case for o_b_pv4_0_0_get_customers_minimal_at_any_bank

        Get Customers Minimal at Any Bank
        """
        pass

    def test_o_b_pv4_0_0_get_my_correlated_entities(self):
        """
        Test case for o_b_pv4_0_0_get_my_correlated_entities

        Get Correlated Entities for the current User
        """
        pass

    def test_o_b_pv4_0_0_get_user_customer_links_by_customer_id(self):
        """
        Test case for o_b_pv4_0_0_get_user_customer_links_by_customer_id

        Get User Customer Links by Customer
        """
        pass

    def test_o_b_pv4_0_0_get_user_customer_links_by_user_id(self):
        """
        Test case for o_b_pv4_0_0_get_user_customer_links_by_user_id

        Get User Customer Links by User
        """
        pass

    def test_o_b_pv4_0_0_update_customer_attribute(self):
        """
        Test case for o_b_pv4_0_0_update_customer_attribute

        Update Customer Attribute
        """
        pass

    def test_o_b_pv5_0_0_create_customer(self):
        """
        Test case for o_b_pv5_0_0_create_customer

        Create Customer
        """
        pass

    def test_o_b_pv5_0_0_create_customer_account_link(self):
        """
        Test case for o_b_pv5_0_0_create_customer_account_link

        Create Customer Account Link
        """
        pass

    def test_o_b_pv5_0_0_delete_customer_account_link_by_id(self):
        """
        Test case for o_b_pv5_0_0_delete_customer_account_link_by_id

        Delete Customer Account Link
        """
        pass

    def test_o_b_pv5_0_0_get_customer_account_link_by_id(self):
        """
        Test case for o_b_pv5_0_0_get_customer_account_link_by_id

        Get Customer Account Link by Id
        """
        pass

    def test_o_b_pv5_0_0_get_customer_account_links_by_account_id(self):
        """
        Test case for o_b_pv5_0_0_get_customer_account_links_by_account_id

        Get Customer Account Links by ACCOUNT_ID
        """
        pass

    def test_o_b_pv5_0_0_get_customer_account_links_by_customer_id(self):
        """
        Test case for o_b_pv5_0_0_get_customer_account_links_by_customer_id

        Get Customer Account Links by CUSTOMER_ID
        """
        pass

    def test_o_b_pv5_0_0_get_customer_overview(self):
        """
        Test case for o_b_pv5_0_0_get_customer_overview

        Get Customer Overview
        """
        pass

    def test_o_b_pv5_0_0_get_customer_overview_flat(self):
        """
        Test case for o_b_pv5_0_0_get_customer_overview_flat

        Get Customer Overview Flat
        """
        pass

    def test_o_b_pv5_0_0_get_customers_at_one_bank(self):
        """
        Test case for o_b_pv5_0_0_get_customers_at_one_bank

        Get Customers at Bank
        """
        pass

    def test_o_b_pv5_0_0_get_customers_minimal_at_one_bank(self):
        """
        Test case for o_b_pv5_0_0_get_customers_minimal_at_one_bank

        Get Customers Minimal at Bank
        """
        pass

    def test_o_b_pv5_0_0_get_my_customers_at_any_bank(self):
        """
        Test case for o_b_pv5_0_0_get_my_customers_at_any_bank

        Get My Customers
        """
        pass

    def test_o_b_pv5_0_0_get_my_customers_at_bank(self):
        """
        Test case for o_b_pv5_0_0_get_my_customers_at_bank

        Get My Customers at Bank
        """
        pass

    def test_o_b_pv5_0_0_update_customer_account_link_by_id(self):
        """
        Test case for o_b_pv5_0_0_update_customer_account_link_by_id

        Update Customer Account Link by Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
