# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from obp_python.configuration import Configuration


class AccountNotificationWebhookPostJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'http_method': 'str',
        'http_protocol': 'str'
    }

    attribute_map = {
        'url': 'url',
        'http_method': 'http_method',
        'http_protocol': 'http_protocol'
    }

    def __init__(self, url=None, http_method=None, http_protocol=None, _configuration=None):  # noqa: E501
        """AccountNotificationWebhookPostJson - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._url = None
        self._http_method = None
        self._http_protocol = None
        self.discriminator = None

        self.url = url
        self.http_method = http_method
        self.http_protocol = http_protocol

    @property
    def url(self):
        """Gets the url of this AccountNotificationWebhookPostJson.  # noqa: E501


        :return: The url of this AccountNotificationWebhookPostJson.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AccountNotificationWebhookPostJson.


        :param url: The url of this AccountNotificationWebhookPostJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def http_method(self):
        """Gets the http_method of this AccountNotificationWebhookPostJson.  # noqa: E501


        :return: The http_method of this AccountNotificationWebhookPostJson.  # noqa: E501
        :rtype: str
        """
        return self._http_method

    @http_method.setter
    def http_method(self, http_method):
        """Sets the http_method of this AccountNotificationWebhookPostJson.


        :param http_method: The http_method of this AccountNotificationWebhookPostJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and http_method is None:
            raise ValueError("Invalid value for `http_method`, must not be `None`")  # noqa: E501

        self._http_method = http_method

    @property
    def http_protocol(self):
        """Gets the http_protocol of this AccountNotificationWebhookPostJson.  # noqa: E501


        :return: The http_protocol of this AccountNotificationWebhookPostJson.  # noqa: E501
        :rtype: str
        """
        return self._http_protocol

    @http_protocol.setter
    def http_protocol(self, http_protocol):
        """Sets the http_protocol of this AccountNotificationWebhookPostJson.


        :param http_protocol: The http_protocol of this AccountNotificationWebhookPostJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and http_protocol is None:
            raise ValueError("Invalid value for `http_protocol`, must not be `None`")  # noqa: E501

        self._http_protocol = http_protocol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountNotificationWebhookPostJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountNotificationWebhookPostJson):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccountNotificationWebhookPostJson):
            return True

        return self.to_dict() != other.to_dict()
