# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from obp_python.configuration import Configuration


class AddCustomerMessageJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'from_department': 'str',
        'from_person': 'str'
    }

    attribute_map = {
        'message': 'message',
        'from_department': 'from_department',
        'from_person': 'from_person'
    }

    def __init__(self, message=None, from_department=None, from_person=None, _configuration=None):  # noqa: E501
        """AddCustomerMessageJson - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._message = None
        self._from_department = None
        self._from_person = None
        self.discriminator = None

        self.message = message
        self.from_department = from_department
        self.from_person = from_person

    @property
    def message(self):
        """Gets the message of this AddCustomerMessageJson.  # noqa: E501


        :return: The message of this AddCustomerMessageJson.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this AddCustomerMessageJson.


        :param message: The message of this AddCustomerMessageJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def from_department(self):
        """Gets the from_department of this AddCustomerMessageJson.  # noqa: E501


        :return: The from_department of this AddCustomerMessageJson.  # noqa: E501
        :rtype: str
        """
        return self._from_department

    @from_department.setter
    def from_department(self, from_department):
        """Sets the from_department of this AddCustomerMessageJson.


        :param from_department: The from_department of this AddCustomerMessageJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and from_department is None:
            raise ValueError("Invalid value for `from_department`, must not be `None`")  # noqa: E501

        self._from_department = from_department

    @property
    def from_person(self):
        """Gets the from_person of this AddCustomerMessageJson.  # noqa: E501


        :return: The from_person of this AddCustomerMessageJson.  # noqa: E501
        :rtype: str
        """
        return self._from_person

    @from_person.setter
    def from_person(self, from_person):
        """Sets the from_person of this AddCustomerMessageJson.


        :param from_person: The from_person of this AddCustomerMessageJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and from_person is None:
            raise ValueError("Invalid value for `from_person`, must not be `None`")  # noqa: E501

        self._from_person = from_person

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddCustomerMessageJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddCustomerMessageJson):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddCustomerMessageJson):
            return True

        return self.to_dict() != other.to_dict()
