# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from obp_python.configuration import Configuration


class PostTaxResidenceJsonV310(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'str',
        'tax_number': 'str'
    }

    attribute_map = {
        'domain': 'domain',
        'tax_number': 'tax_number'
    }

    def __init__(self, domain=None, tax_number=None, _configuration=None):  # noqa: E501
        """PostTaxResidenceJsonV310 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._domain = None
        self._tax_number = None
        self.discriminator = None

        self.domain = domain
        self.tax_number = tax_number

    @property
    def domain(self):
        """Gets the domain of this PostTaxResidenceJsonV310.  # noqa: E501


        :return: The domain of this PostTaxResidenceJsonV310.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this PostTaxResidenceJsonV310.


        :param domain: The domain of this PostTaxResidenceJsonV310.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def tax_number(self):
        """Gets the tax_number of this PostTaxResidenceJsonV310.  # noqa: E501


        :return: The tax_number of this PostTaxResidenceJsonV310.  # noqa: E501
        :rtype: str
        """
        return self._tax_number

    @tax_number.setter
    def tax_number(self, tax_number):
        """Sets the tax_number of this PostTaxResidenceJsonV310.


        :param tax_number: The tax_number of this PostTaxResidenceJsonV310.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and tax_number is None:
            raise ValueError("Invalid value for `tax_number`, must not be `None`")  # noqa: E501

        self._tax_number = tax_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostTaxResidenceJsonV310, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostTaxResidenceJsonV310):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostTaxResidenceJsonV310):
            return True

        return self.to_dict() != other.to_dict()
