# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.0.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from obp_python.configuration import Configuration


class UserCustomerLinkJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_active': 'bool',
        'customer_id': 'str',
        'user_id': 'str',
        'date_inserted': 'date',
        'user_customer_link_id': 'str'
    }

    attribute_map = {
        'is_active': 'is_active',
        'customer_id': 'customer_id',
        'user_id': 'user_id',
        'date_inserted': 'date_inserted',
        'user_customer_link_id': 'user_customer_link_id'
    }

    def __init__(self, is_active=None, customer_id=None, user_id=None, date_inserted=None, user_customer_link_id=None, _configuration=None):  # noqa: E501
        """UserCustomerLinkJson - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_active = None
        self._customer_id = None
        self._user_id = None
        self._date_inserted = None
        self._user_customer_link_id = None
        self.discriminator = None

        self.is_active = is_active
        self.customer_id = customer_id
        self.user_id = user_id
        self.date_inserted = date_inserted
        self.user_customer_link_id = user_customer_link_id

    @property
    def is_active(self):
        """Gets the is_active of this UserCustomerLinkJson.  # noqa: E501


        :return: The is_active of this UserCustomerLinkJson.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this UserCustomerLinkJson.


        :param is_active: The is_active of this UserCustomerLinkJson.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and is_active is None:
            raise ValueError("Invalid value for `is_active`, must not be `None`")  # noqa: E501

        self._is_active = is_active

    @property
    def customer_id(self):
        """Gets the customer_id of this UserCustomerLinkJson.  # noqa: E501


        :return: The customer_id of this UserCustomerLinkJson.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this UserCustomerLinkJson.


        :param customer_id: The customer_id of this UserCustomerLinkJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def user_id(self):
        """Gets the user_id of this UserCustomerLinkJson.  # noqa: E501


        :return: The user_id of this UserCustomerLinkJson.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserCustomerLinkJson.


        :param user_id: The user_id of this UserCustomerLinkJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def date_inserted(self):
        """Gets the date_inserted of this UserCustomerLinkJson.  # noqa: E501


        :return: The date_inserted of this UserCustomerLinkJson.  # noqa: E501
        :rtype: date
        """
        return self._date_inserted

    @date_inserted.setter
    def date_inserted(self, date_inserted):
        """Sets the date_inserted of this UserCustomerLinkJson.


        :param date_inserted: The date_inserted of this UserCustomerLinkJson.  # noqa: E501
        :type: date
        """
        if self._configuration.client_side_validation and date_inserted is None:
            raise ValueError("Invalid value for `date_inserted`, must not be `None`")  # noqa: E501

        self._date_inserted = date_inserted

    @property
    def user_customer_link_id(self):
        """Gets the user_customer_link_id of this UserCustomerLinkJson.  # noqa: E501


        :return: The user_customer_link_id of this UserCustomerLinkJson.  # noqa: E501
        :rtype: str
        """
        return self._user_customer_link_id

    @user_customer_link_id.setter
    def user_customer_link_id(self, user_customer_link_id):
        """Sets the user_customer_link_id of this UserCustomerLinkJson.


        :param user_customer_link_id: The user_customer_link_id of this UserCustomerLinkJson.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and user_customer_link_id is None:
            raise ValueError("Invalid value for `user_customer_link_id`, must not be `None`")  # noqa: E501

        self._user_customer_link_id = user_customer_link_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserCustomerLinkJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCustomerLinkJson):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserCustomerLinkJson):
            return True

        return self.to_dict() != other.to_dict()
